auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
categories: [Technology, Thinking, Arts, Science, Fitness]
excerpt_separator: "<!--more-->"
destination: _site
url: http://www.benjvi.com
