auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title
categories: [Technology, Thinking, Arts, Science, Fitness]
excerpt_separator: "<!--more-->"
destination: _site
url: http://192.168.1.60:31421
plugins:
 - jemoji
css_flavour: standard
