auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title
categories: [Technology, Thinking, Arts, Science, Fitness]
excerpt_separator: "<!--more-->"
destination: _site
url: https://blog.pi.bjv.me
plugins:
 - jemoji
css_flavour: standard
