{
 "title": "Blog Content",
 "time": { "from": "now-180d", "to": "now" },
 "panels": [
  { "title": "Long-term View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blog Posts Published",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- number of posts published this year\n-- and previous years\n-- decided that I don't really care how long each post is, just how many posts I publish\n-- maybe average number of words is interesting, but should be evaluated post-by-posts\nselect \n  date_trunc('year', first) as \"time\",\n  count(distinct file)\nfrom published_edit\nWHERE\n  $__timeFilter(first)\n  group by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blog Posts Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n  date_trunc('month', author_when) as \"time\",\n  count(*) as \"value\"\nfrom (\n  select *\n  from published_post_commits\n  union\n  select *\n  from draft_post_commits\n) as post_commits\nwhere \n  $__timeFilter(author_when)\ngroup by 1\norder by 1;\n\n"
    }
   ]
  },
  {
   "title": "Published This Year",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   count(*)\nFROM published_edit\nWHERE\n  first > date_trunc('year', now())"
    }
   ]
  },
  {
   "title": "Commits This Year",
   "type": "stat",
   "description": "Counting only Content-Related Commits",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   count(*)\nfrom (\n  select *\n  from published_post_commits\n  union\n  select *\n  from draft_post_commits\n) as post_commits\nWHERE\n  author_when > date_trunc('year', now())"
    }
   ]
  },
  { "title": "Recent Posts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Recently Published Posts",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  title,\n  first as \"publish date\",\n  extract(days from (now() - first)) as \"days old\"\nFROM published_edit p\nWHERE\n  $__timeFilter(p.first)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg time To Publish (days)",
   "type": "stat",
   "description": "How long it takes to publish after a draft is first checked-in",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  p.first as \"time\",\n  extract(days from (p.first - f.time))\nfrom published_edit p\nleft join first_draft_edit f\non p.title=f.title\nwhere \n  $__timeFilter(time)\n  and f.time is not null\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg time To Complete a Post (days)",
   "type": "stat",
   "description": "How long until I stop working on after the first draft is checked in",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  p.first as \"time\",\n  extract(days from (p.last - f.time))\nfrom published_edit p\nleft join first_edit f\non p.title=f.title\nwhere \n  $__timeFilter(time)\n  and f.time is not null\nORDER BY 1"
    }
   ]
  },
  { "title": "Drafts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of Unfinished Drafts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  author_when as \"time\",\n  count(*)\nfrom draft_post_details\njoin blog_repo_commits\non commit_id = blog_repo_commits.id\nwhere\n  $__timeFilter(author_when)\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unfinished Drafts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "rawSql": "select \n  name,\n  extract(days from draft_age) as \"days_old\"\nfrom draft_post_details\njoin latest_commit\non draft_post_details.commit_id=latest_commit.id;\n"
    }
   ]
  },
  { "title": "Delivery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Time taken to deploy an updated post",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  publish_commit_time as \"time\",\n  minutes_between_publish_and_deploy\nFROM post_publish_to_deploy\nWHERE\n  $__timeFilter(publish_commit_time)\nORDER BY 1"
    }
   ]
  }
 ]
}