name: Promote to prod

on:
  push:
    branches:
    - master
  repository_dispatch:
    types:
      - "manual-deploy" 

jobs:
  pipeline:
    environment: default
    env:
      GH_REPO_PAT_TOKEN: ${{ secrets.GH_REPO_PAT_TOKEN }}
    runs-on:
    - ubuntu-latest
    steps:
      - name: Triggered by event
        if: github.event_name == 'repository_dispatch'
        run: 'echo "Triggered by: ${{ github.event.client_payload.user }}"'

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_PAT_TOKEN }}

      - name: Publish docker image
        run: 'bash .github/scripts/publish-image.sh'

      - name: Promote manifests
        with:
          entrypoint: '.github/scripts/gitops-deploy.sh'
        uses: docker://benjvi/prify:latest
